# Sirai Configuration Sample
# This file should be placed at ~/.sirai/config.yaml

# Language Model (LLM) Configuration
llm:
  # Provider-specific configurations
  # These can be referenced by name in taskPlanning.providerConfig
  providers:
    # OpenAI configuration
    openai:
      enabled: true
      provider: openai
      model: gpt-4
      apiKey: your_openai_key_here

    # Anthropic configuration
    anthropic:
      enabled: true
      provider: anthropic
      model: claude-3-7-sonnet-latest
      apiKey: your_anthropic_key_here

    # Google configuration
    google:
      enabled: true
      provider: google
      model: gemini-2.5-pro-exp-03-25
      apiKey: your_google_key_here

    # Ollama configuration
    ollama:
      enabled: true
      provider: ollama
      model: command-r
      baseUrl: http://localhost:11434

# Execution Configuration
execution:
  parallel: false                      # Whether to execute tasks in parallel
  maxParallel: 2                       # Maximum number of parallel tasks

# Output Configuration
output:
  colorEnabled: true                   # Enable colored output
  syntaxHighlighting: true             # Enable syntax highlighting for code

# Prompts Configuration
prompts:
  directory: ~/.sirai/prompts           # Directory to store saved prompts

# Chat Configuration
chat:
  saveHistory: true                    # Whether to save chat history between sessions
  maxHistoryMessages: 20               # Maximum number of messages to keep in history

# Task Planning Configuration
taskPlanning:
  enabled: true
  preferredProvider: anthropic         # Default provider for task planning

  # Task-specific provider configuration
  # This allows you to use different providers for different types of tasks
  providerConfig:
    # Example: Use different providers for different task types
    planning:
      provider: anthropic
      model: claude-3-7-sonnet-latest

    coding:
      provider: google
      model: gemini-2.5-pro-exp-03-25

    default:
      provider: openai
      model: gpt-4o
